/**
 * Shared vocabulary for the catalogue. Enumerating these here gives the API a
 * single source of truth for validation, documentation and the client UI.
 */
const HOTEL_CERTIFICATIONS = Object.freeze([
  'GREEN_KEY', 'EU_ECOLABEL', 'LEED', 'BREEAM', 'GREEN_GLOBE', 'BIOSPHERE', 'EARTHCHECK', 'NORDIC_SWAN',
]);

const HOTEL_FEATURES = Object.freeze([
  'RENEWABLE_ENERGY', 'WATER_RECYCLING', 'ZERO_WASTE', 'LOCAL_FOOD', 'EV_CHARGING', 'BIKE_RENTAL',
  'PLASTIC_FREE', 'CARBON_NEUTRAL', 'GREEN_ROOF', 'ORGANIC_LINEN', 'COMPOSTING', 'RAINWATER_HARVESTING',
  'NO_DAILY_HOUSEKEEPING', 'PUBLIC_TRANSPORT_ACCESS', 'HERITAGE_RETROFIT', 'PASSIVE_HOUSE',
]);

const RESTAURANT_CERTIFICATIONS = Object.freeze([
  'SUSTAINABLE_RESTAURANT_ASSOCIATION', 'GREEN_RESTAURANT_ASSOCIATION', 'ORGANIC_CERTIFIED', 'MSC_CHAIN_OF_CUSTODY', 'FAIRTRADE',
]);

const RESTAURANT_FEATURES = Object.freeze([
  'LOCAL_SOURCING', 'ORGANIC', 'SEASONAL_MENU', 'ZERO_WASTE', 'PLANT_BASED', 'FAIR_TRADE', 'COMPOSTING',
  'NO_SINGLE_USE_PLASTIC', 'RENEWABLE_ENERGY', 'FOOD_RESCUE', 'TAP_WATER_ONLY', 'OWN_GARDEN',
]);

const DIETARY_OPTIONS = Object.freeze(['VEGAN', 'VEGETARIAN', 'GLUTEN_FREE', 'DAIRY_FREE', 'NUT_FREE', 'HALAL', 'KOSHER']);

const BOOKING_TYPES = Object.freeze(['HOTEL', 'RESTAURANT']);
const BOOKING_STATUSES = Object.freeze(['CONFIRMED', 'CANCELLED']);

/** Reservation length used for restaurant capacity planning, in minutes. */
const RESTAURANT_SEATING_MINUTES = 90;
/** Interval between bookable restaurant slots, in minutes. */
const RESTAURANT_SLOT_MINUTES = 30;

module.exports = {
  HOTEL_CERTIFICATIONS,
  HOTEL_FEATURES,
  RESTAURANT_CERTIFICATIONS,
  RESTAURANT_FEATURES,
  DIETARY_OPTIONS,
  BOOKING_TYPES,
  BOOKING_STATUSES,
  RESTAURANT_SEATING_MINUTES,
  RESTAURANT_SLOT_MINUTES,
};
